name: Publish Site
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Write mkdocs-material-insiders to requirements file
        run: echo "git+https://${{ secrets.INSIDERS_GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git" > requirements.txt

      - name: Build MkDocs site
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: new.silk.one
          REQUIREMENTS: requirements.txt