name: Publish Site
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install Material for MkDocs Insiders
        run: pip install git+https://github.com/squidfunk/mkdocs-material-insiders.git

      - name: Build MkDocs site
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: new.silk.one